name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Rc.DiscordBot.sln
    - name: Test
      run: dotnet test src/Rc.DiscordBot.sln --verbosity normal
    # Linux Standalone
    - name: Publish Linux x64 Standalone
      run: dotnet publish src/src/Rc.DiscordBot.Worker.Linux/Rc.DiscordBot.Worker.Linux.csproj --self-contained true -p:PublishTrimmed=true -c release -o publish -r linux-x64 -p:PublishDir=publish/linux-x64-standalone
    - name: Upload Linux x64 Standalone Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux x64 Standalone
        path: /home/runner/work/DiscordBot/DiscordBot/src/src/Rc.DiscordBot.Worker.Linux/publish/linux-x64-standalone/  
    # Linux
    - name: Publish x64 Linux
      run: dotnet publish src/src/Rc.DiscordBot.Worker.Linux/Rc.DiscordBot.Worker.Linux.csproj --self-contained false -c release -o publish -r linux-x64 -p:PublishDir=publish/linux-x64
    - name: Upload Linux x64 Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux x64
        path: /home/runner/work/DiscordBot/DiscordBot/src/src/Rc.DiscordBot.Worker.Linux/publish/linux-x64/
   # Windows x64 Standalone
    - name: Publish Windows x64 Standalone
      run: dotnet publish src/src/Rc.DiscordBot.Worker.Windows/Rc.DiscordBot.Worker.Windows.csproj --self-contained true -p:PublishTrimmed=true -c release -o publish -r win-x64 -p:PublishDir=publish/windows-x64-standalone
    - name: Upload Windows x64 Standalone Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows x64 Standalone
        path: /home/runner/work/DiscordBot/DiscordBot/src/src/Rc.DiscordBot.Worker.Windows/publish/windows-x64-standalone/  
    # Windows x64
    - name: Publish Windows x64
      run: dotnet publish src/src/Rc.DiscordBot.Worker.Windows/Rc.DiscordBot.Worker.Windows.csproj --self-contained false -c release -o publish -r win-x64 -p:PublishDir=publish/windows-x64
    - name: Upload Windows x64 Standalone Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows x64
        path: /home/runner/work/DiscordBot/DiscordBot/src/src/Rc.DiscordBot.Worker.Windows/publish/windows-x64
   

      
      
